### ISSUE TITLE
failed to extract the gene 'eae' from Genbank file

### ISSUE THREAD

**Issue by liuqian666** [linzhi2013/gbseqextractor#3]
Sorry for disturb you.
I want to extract the gene named 'eae' from batch GBK files, here're my commands of one GBK files

`gbseqextractor -f ESA174_C.gbk -prefix ESA174_eae -seqPrefix ESA174_eae_ `

and I modified gbseqextractor.py line 169 and 170 as 
```
gene = "eae"
product = "Intimin"
```

However, I get the whole CDS sequence of GBK files
Can you help me solve this problem?
Thank you very much!

**Comment by linzhi2013** [comment]
Could you please tell me the accession number of the record you are working with or send me the Genbank file you have directly?

PS: this tool has been added to https://github.com/linzhi2013/MitoZ/wiki/The-%27mitoz-tools-gbseqextractor%27-command. You could try it first. I don't remember if there were some updates.

**Comment by liuqian666** [comment]
> Could you please tell me the accession number of the record you are working with or send me the Genbank file you have directly?
> 
> PS: this tool has been added to https://github.com/linzhi2013/MitoZ/wiki/The-%27mitoz-tools-gbseqextractor%27-command. You could try it first. I don't remember if there were some updates.

Genbank: GCA_000512125.1
And I‘ll try mitoz now
Thank you very much!

**Comment by linzhi2013** [comment]
I see why.

Because this genebank file doesn't have `gene=` tag,

instead, it has 
```
     gene            2872..2988
                     /locus_tag="EAKF1_ch0005"
     CDS             2872..2988
                     /locus_tag="EAKF1_ch0005"
```

which doesn't work with my script (either MitoZ-tool). This is due to there being too many variations of different usages of the GenBank format.

You can modify the script to meet your purpose.

Cheers

**Comment by liuqian666** [comment]
> I see why.
> 
> Because this genebank file doesn't have `gene=` tag,
> 
> instead, it has
> 
> ```
>      gene            2872..2988
>                      /locus_tag="EAKF1_ch0005"
>      CDS             2872..2988


>                      /locus_tag="EAKF1_ch0005"
> ```
> 
> which doesn't work with my script (either MitoZ-tool). This is due to there being too many variations of different usages of the GenBank format.
> 
> You can modify the script to meet your purpose.
> 
> Cheers

[GCA_000512125.1_prokka.gbk.txt](https://github.com/linzhi2013/gbseqextractor/files/9609137/GCA_000512125.1_prokka.gbk.txt)


I‘ve tried to download the genome files and annotated by prokka. 
Then, I used the output file of prokka (gbk) whchi contained 'gene=tag' as the input files of gbseqextractor, but it's still failed. 
It's a little bit hard for me to modified the scripts, beacuse I am not good at writing code.
Is there any example for gbk files that can work with your tools?
Thank you very much!🌹

**Comment by linzhi2013** [comment]
Hi, I check your file. It only has `CDS` features:

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/6203542/191585123-a8b1c877-66b9-4684-8d8a-7ea70c389a68.png">

If you want to extract **gene** features, the file should have **gene** features.

Solution: try ` mitoz-tools  gbseqextractor -types CDS` instead

```
  -types {CDS,rRNA,tRNA,wholeseq,gene} [{CDS,rRNA,tRNA,wholeseq,gene} ...]
                        what kind of genes you want to extract? wholeseq for whole fasta seq. WARNING: Each
                        sequence in the result files corresponds to ONE feature in the GenBank file, I will NOT
                        combine multiple CDS of the same gene into ONE! [CDS]
```

For the whole help info:
```bash
$ mitoz-tools  gbseqextractor -h
usage: mitoz-tools gbseqextractor [-h] -f <STR> -prefix <STR> [-seqPrefix <STR>]
                                  [-types {CDS,rRNA,tRNA,wholeseq,gene} [{CDS,rRNA,tRNA,wholeseq,gene} ...]]
                                  [-cds_translation] [-gi] [-p] [-t] [-rv] [-s] [-l] [-F]

Extract any CDS or rNRA or tRNA DNA sequences of genes from Genbank file.

Seqid will be the value of '/gene=' or '/product=', if they both were not
present, the gene will not be output!

version 20201128:
    Now we can handle compounlocation (feature location with "join")!
    We can also output the translation for each CDS (retrived from '/translation=')

Please cite:
Guanliang Meng, Yiyuan Li, Chentao Yang, Shanlin Liu,
MitoZ: a toolkit for animal mitochondrial genome assembly, annotation
and visualization, Nucleic Acids Research, https://doi.org/10.1093/nar/gkz173

optional arguments:
  -h, --help            show this help message and exit
  -f <STR>              Genbank file
  -prefix <STR>         prefix of output file. required.
  -seqPrefix <STR>      prefix of each seq id. default: None
  -types {CDS,rRNA,tRNA,wholeseq,gene} [{CDS,rRNA,tRNA,wholeseq,gene} ...]
                        what kind of genes you want to extract? wholeseq for whole fasta seq. WARNING: Each
                        sequence in the result files corresponds to ONE feature in the GenBank file, I will NOT
                        combine multiple CDS of the same gene into ONE! [CDS]
  -cds_translation      Also output translated CDS (required -types CDS). The translations are retrived directly
                        from the '/translation=' key word. [False]
  -gi                   use gi number as sequence ID instead of accession number when " gi number is present.
                        (default: accession number)
  -p                    output the position information on the ID line. Warning: the position on ID line is 0
                        left-most! [False]
  -t                    output the taxonomy lineage on ID line [False]
  -rv                   reverse and complement the output sequences if they are on the 3'-5' direction [True]
  -s                    output the species name on the ID line [False]
  -l                    output the seq length on the ID line [False]
  -F                    only output full length genes,i.e., exclude the genes with '>' or '<' in their location
                        [False]
```

**Comment by linzhi2013** [comment]
A normal GenBank file is like https://www.ncbi.nlm.nih.gov/nuccore/NC_023380.1

<img width="882" alt="image" src="https://user-images.githubusercontent.com/6203542/191585675-f4d32d8d-2cfa-459e-8135-66ab7f795cf7.png">

**Comment by liuqian666** [comment]
> A normal GenBank file is like https://www.ncbi.nlm.nih.gov/nuccore/NC_023380.1
> 
> <img alt="image" width="882" src="https://user-images.githubusercontent.com/6203542/191585675-f4d32d8d-2cfa-459e-8135-66ab7f795cf7.png">

Oh, I see~
Thank you very very much 
Best wishes
